//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linxens.Core.QADServicesV2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-qad-com:xml-services", ConfigurationName="QADServicesV2.QdocWebService")]
    public interface QdocWebService {
        
        // CODEGEN: Generating message contract since the operation golfRepetitive is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Linxens.Core.QADServicesV2.processGolfRepetitiveResponse golfRepetitive(Linxens.Core.QADServicesV2.processGolfRepetitiveRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool suppressResponseDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=0)]
        public bool suppressResponseDetail {
            get {
                return this.suppressResponseDetailField;
            }
            set {
                this.suppressResponseDetailField = value;
                this.RaisePropertyChanged("suppressResponseDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReplyToType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services:common")]
    public partial class Temp_err_msg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> tt_levelField;
        
        private string tt_msg_contextField;
        
        private string tt_msg_dataField;
        
        private string tt_msg_datetimeField;
        
        private string tt_msg_descField;
        
        private string tt_msg_fieldField;
        
        private System.Nullable<int> tt_msg_indexField;
        
        private string[] tt_msg_keysField;
        
        private string tt_msg_nbrField;
        
        private System.Nullable<bool> tt_msg_processedField;
        
        private string tt_msg_sevField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> tt_level {
            get {
                return this.tt_levelField;
            }
            set {
                this.tt_levelField = value;
                this.RaisePropertyChanged("tt_level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string tt_msg_context {
            get {
                return this.tt_msg_contextField;
            }
            set {
                this.tt_msg_contextField = value;
                this.RaisePropertyChanged("tt_msg_context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string tt_msg_data {
            get {
                return this.tt_msg_dataField;
            }
            set {
                this.tt_msg_dataField = value;
                this.RaisePropertyChanged("tt_msg_data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string tt_msg_datetime {
            get {
                return this.tt_msg_datetimeField;
            }
            set {
                this.tt_msg_datetimeField = value;
                this.RaisePropertyChanged("tt_msg_datetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string tt_msg_desc {
            get {
                return this.tt_msg_descField;
            }
            set {
                this.tt_msg_descField = value;
                this.RaisePropertyChanged("tt_msg_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string tt_msg_field {
            get {
                return this.tt_msg_fieldField;
            }
            set {
                this.tt_msg_fieldField = value;
                this.RaisePropertyChanged("tt_msg_field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> tt_msg_index {
            get {
                return this.tt_msg_indexField;
            }
            set {
                this.tt_msg_indexField = value;
                this.RaisePropertyChanged("tt_msg_index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tt_msg_keys", IsNullable=true, Order=7)]
        public string[] tt_msg_keys {
            get {
                return this.tt_msg_keysField;
            }
            set {
                this.tt_msg_keysField = value;
                this.RaisePropertyChanged("tt_msg_keys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string tt_msg_nbr {
            get {
                return this.tt_msg_nbrField;
            }
            set {
                this.tt_msg_nbrField = value;
                this.RaisePropertyChanged("tt_msg_nbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> tt_msg_processed {
            get {
                return this.tt_msg_processedField;
            }
            set {
                this.tt_msg_processedField = value;
                this.RaisePropertyChanged("tt_msg_processed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string tt_msg_sev {
            get {
                return this.tt_msg_sevField;
            }
            set {
                this.tt_msg_sevField = value;
                this.RaisePropertyChanged("tt_msg_sev");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services")]
    public partial class WSDLGolfRepetitiveResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private TtContext[] dsSessionContextField;
        
        private Temp_err_msg[] dsExceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ttContext", IsNullable=false)]
        public TtContext[] dsSessionContext {
            get {
                return this.dsSessionContextField;
            }
            set {
                this.dsSessionContextField = value;
                this.RaisePropertyChanged("dsSessionContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("temp_err_msg", IsNullable=false)]
        public Temp_err_msg[] dsExceptions {
            get {
                return this.dsExceptionsField;
            }
            set {
                this.dsExceptionsField = value;
                this.RaisePropertyChanged("dsExceptions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services:common")]
    public partial class TtContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string propertyQualifierField;
        
        private string propertyNameField;
        
        private string propertyValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string propertyQualifier {
            get {
                return this.propertyQualifierField;
            }
            set {
                this.propertyQualifierField = value;
                this.RaisePropertyChanged("propertyQualifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string propertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
                this.RaisePropertyChanged("propertyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string propertyValue {
            get {
                return this.propertyValueField;
            }
            set {
                this.propertyValueField = value;
                this.RaisePropertyChanged("propertyValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services")]
    public partial class Tt_GolfDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> tt_srnoField;
        
        private bool tt_srnoFieldSpecified;
        
        private string tt_empField;
        
        private string tt_tr_typeField;
        
        private string tt_lineField;
        
        private string tt_partField;
        
        private System.Nullable<int> tt_opField;
        
        private bool tt_opFieldSpecified;
        
        private string tt_wcField;
        
        private string tt_mchField;
        
        private string tt_lblField;
        
        private string tt_t_lblField;
        
        private System.Nullable<decimal> tt_qtyField;
        
        private bool tt_qtyFieldSpecified;
        
        private string tt_rsnField;
        
        private System.Nullable<int> tt_defectsField;
        
        private bool tt_defectsFieldSpecified;
        
        private System.Nullable<int> tt_splicesField;
        
        private bool tt_splicesFieldSpecified;
        
        private string tt_p_dateField;
        
        private string tt_printerField;
        
        private string tt_shiptoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> tt_srno {
            get {
                return this.tt_srnoField;
            }
            set {
                this.tt_srnoField = value;
                this.RaisePropertyChanged("tt_srno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tt_srnoSpecified {
            get {
                return this.tt_srnoFieldSpecified;
            }
            set {
                this.tt_srnoFieldSpecified = value;
                this.RaisePropertyChanged("tt_srnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string tt_emp {
            get {
                return this.tt_empField;
            }
            set {
                this.tt_empField = value;
                this.RaisePropertyChanged("tt_emp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string tt_tr_type {
            get {
                return this.tt_tr_typeField;
            }
            set {
                this.tt_tr_typeField = value;
                this.RaisePropertyChanged("tt_tr_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string tt_line {
            get {
                return this.tt_lineField;
            }
            set {
                this.tt_lineField = value;
                this.RaisePropertyChanged("tt_line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string tt_part {
            get {
                return this.tt_partField;
            }
            set {
                this.tt_partField = value;
                this.RaisePropertyChanged("tt_part");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> tt_op {
            get {
                return this.tt_opField;
            }
            set {
                this.tt_opField = value;
                this.RaisePropertyChanged("tt_op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tt_opSpecified {
            get {
                return this.tt_opFieldSpecified;
            }
            set {
                this.tt_opFieldSpecified = value;
                this.RaisePropertyChanged("tt_opSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string tt_wc {
            get {
                return this.tt_wcField;
            }
            set {
                this.tt_wcField = value;
                this.RaisePropertyChanged("tt_wc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string tt_mch {
            get {
                return this.tt_mchField;
            }
            set {
                this.tt_mchField = value;
                this.RaisePropertyChanged("tt_mch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string tt_lbl {
            get {
                return this.tt_lblField;
            }
            set {
                this.tt_lblField = value;
                this.RaisePropertyChanged("tt_lbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string tt_t_lbl {
            get {
                return this.tt_t_lblField;
            }
            set {
                this.tt_t_lblField = value;
                this.RaisePropertyChanged("tt_t_lbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> tt_qty {
            get {
                return this.tt_qtyField;
            }
            set {
                this.tt_qtyField = value;
                this.RaisePropertyChanged("tt_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tt_qtySpecified {
            get {
                return this.tt_qtyFieldSpecified;
            }
            set {
                this.tt_qtyFieldSpecified = value;
                this.RaisePropertyChanged("tt_qtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string tt_rsn {
            get {
                return this.tt_rsnField;
            }
            set {
                this.tt_rsnField = value;
                this.RaisePropertyChanged("tt_rsn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> tt_defects {
            get {
                return this.tt_defectsField;
            }
            set {
                this.tt_defectsField = value;
                this.RaisePropertyChanged("tt_defects");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tt_defectsSpecified {
            get {
                return this.tt_defectsFieldSpecified;
            }
            set {
                this.tt_defectsFieldSpecified = value;
                this.RaisePropertyChanged("tt_defectsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> tt_splices {
            get {
                return this.tt_splicesField;
            }
            set {
                this.tt_splicesField = value;
                this.RaisePropertyChanged("tt_splices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tt_splicesSpecified {
            get {
                return this.tt_splicesFieldSpecified;
            }
            set {
                this.tt_splicesFieldSpecified = value;
                this.RaisePropertyChanged("tt_splicesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string tt_p_date {
            get {
                return this.tt_p_dateField;
            }
            set {
                this.tt_p_dateField = value;
                this.RaisePropertyChanged("tt_p_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string tt_printer {
            get {
                return this.tt_printerField;
            }
            set {
                this.tt_printerField = value;
                this.RaisePropertyChanged("tt_printer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string tt_shipto {
            get {
                return this.tt_shiptoField;
            }
            set {
                this.tt_shiptoField = value;
                this.RaisePropertyChanged("tt_shipto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services")]
    public partial class WSDLGolfRepetitiveType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TtContext[] dsSessionContextField;
        
        private Tt_GolfDataType[] dsGolfRepetitiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ttContext", IsNullable=false)]
        public TtContext[] dsSessionContext {
            get {
                return this.dsSessionContextField;
            }
            set {
                this.dsSessionContextField = value;
                this.RaisePropertyChanged("dsSessionContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tt_GolfData", IsNullable=false)]
        public Tt_GolfDataType[] dsGolfRepetitive {
            get {
                return this.dsGolfRepetitiveField;
            }
            set {
                this.dsGolfRepetitiveField = value;
                this.RaisePropertyChanged("dsGolfRepetitive");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processGolfRepetitiveRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string Action;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string To;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string MessageID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public Linxens.Core.QADServicesV2.ReferenceParametersType ReferenceParameters;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public Linxens.Core.QADServicesV2.ReplyToType ReplyTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-qad-com:xml-services", Order=0)]
        public Linxens.Core.QADServicesV2.WSDLGolfRepetitiveType golfRepetitive;
        
        public processGolfRepetitiveRequest() {
        }
        
        public processGolfRepetitiveRequest(string Action, string To, string MessageID, Linxens.Core.QADServicesV2.ReferenceParametersType ReferenceParameters, Linxens.Core.QADServicesV2.ReplyToType ReplyTo, Linxens.Core.QADServicesV2.WSDLGolfRepetitiveType golfRepetitive) {
            this.Action = Action;
            this.To = To;
            this.MessageID = MessageID;
            this.ReferenceParameters = ReferenceParameters;
            this.ReplyTo = ReplyTo;
            this.golfRepetitive = golfRepetitive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processGolfRepetitiveResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string To;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string Action;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string MessageID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string RelatesTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-qad-com:xml-services", Order=0)]
        public Linxens.Core.QADServicesV2.WSDLGolfRepetitiveResponseType golfRepetitiveResponse;
        
        public processGolfRepetitiveResponse() {
        }
        
        public processGolfRepetitiveResponse(string To, string Action, string MessageID, string RelatesTo, Linxens.Core.QADServicesV2.WSDLGolfRepetitiveResponseType golfRepetitiveResponse) {
            this.To = To;
            this.Action = Action;
            this.MessageID = MessageID;
            this.RelatesTo = RelatesTo;
            this.golfRepetitiveResponse = golfRepetitiveResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QdocWebServiceChannel : Linxens.Core.QADServicesV2.QdocWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QdocWebServiceClient : System.ServiceModel.ClientBase<Linxens.Core.QADServicesV2.QdocWebService>, Linxens.Core.QADServicesV2.QdocWebService {
        
        public QdocWebServiceClient() {
        }
        
        public QdocWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QdocWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QdocWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QdocWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Linxens.Core.QADServicesV2.processGolfRepetitiveResponse Linxens.Core.QADServicesV2.QdocWebService.golfRepetitive(Linxens.Core.QADServicesV2.processGolfRepetitiveRequest request) {
            return base.Channel.golfRepetitive(request);
        }
        
        public string golfRepetitive(ref string Action, ref string To, ref string MessageID, Linxens.Core.QADServicesV2.ReferenceParametersType ReferenceParameters, Linxens.Core.QADServicesV2.ReplyToType ReplyTo, Linxens.Core.QADServicesV2.WSDLGolfRepetitiveType golfRepetitive1, out Linxens.Core.QADServicesV2.WSDLGolfRepetitiveResponseType golfRepetitiveResponse) {
            Linxens.Core.QADServicesV2.processGolfRepetitiveRequest inValue = new Linxens.Core.QADServicesV2.processGolfRepetitiveRequest();
            inValue.Action = Action;
            inValue.To = To;
            inValue.MessageID = MessageID;
            inValue.ReferenceParameters = ReferenceParameters;
            inValue.ReplyTo = ReplyTo;
            inValue.golfRepetitive = golfRepetitive1;
            Linxens.Core.QADServicesV2.processGolfRepetitiveResponse retVal = ((Linxens.Core.QADServicesV2.QdocWebService)(this)).golfRepetitive(inValue);
            To = retVal.To;
            Action = retVal.Action;
            MessageID = retVal.MessageID;
            golfRepetitiveResponse = retVal.golfRepetitiveResponse;
            return retVal.RelatesTo;
        }
    }
}
