//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linxens.Core.QADServices {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:soap-fault:details")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS")]
    public partial class xxm2q01_tt_Error_WarningRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tterr_typeField;
        
        private System.Nullable<int> tterr_srnoField;
        
        private string tterr_codeField;
        
        private string tterr_descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string tterr_type {
            get {
                return this.tterr_typeField;
            }
            set {
                this.tterr_typeField = value;
                this.RaisePropertyChanged("tterr_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> tterr_srno {
            get {
                return this.tterr_srnoField;
            }
            set {
                this.tterr_srnoField = value;
                this.RaisePropertyChanged("tterr_srno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string tterr_code {
            get {
                return this.tterr_codeField;
            }
            set {
                this.tterr_codeField = value;
                this.RaisePropertyChanged("tterr_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string tterr_desc {
            get {
                return this.tterr_descField;
            }
            set {
                this.tterr_descField = value;
                this.RaisePropertyChanged("tterr_desc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS")]
    public partial class xxm2q01_tt_golf_dataRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> ip_srnoField;
        
        private string ip_empField;
        
        private string ip_tr_typeField;
        
        private string ip_lineField;
        
        private string ip_partField;
        
        private System.Nullable<int> ip_opField;
        
        private string ip_wcField;
        
        private string ip_mchField;
        
        private string ip_lblField;
        
        private System.Nullable<decimal> ip_qtyField;
        
        private string ip_rsnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> ip_srno {
            get {
                return this.ip_srnoField;
            }
            set {
                this.ip_srnoField = value;
                this.RaisePropertyChanged("ip_srno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ip_emp {
            get {
                return this.ip_empField;
            }
            set {
                this.ip_empField = value;
                this.RaisePropertyChanged("ip_emp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ip_tr_type {
            get {
                return this.ip_tr_typeField;
            }
            set {
                this.ip_tr_typeField = value;
                this.RaisePropertyChanged("ip_tr_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ip_line {
            get {
                return this.ip_lineField;
            }
            set {
                this.ip_lineField = value;
                this.RaisePropertyChanged("ip_line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ip_part {
            get {
                return this.ip_partField;
            }
            set {
                this.ip_partField = value;
                this.RaisePropertyChanged("ip_part");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> ip_op {
            get {
                return this.ip_opField;
            }
            set {
                this.ip_opField = value;
                this.RaisePropertyChanged("ip_op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ip_wc {
            get {
                return this.ip_wcField;
            }
            set {
                this.ip_wcField = value;
                this.RaisePropertyChanged("ip_wc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ip_mch {
            get {
                return this.ip_mchField;
            }
            set {
                this.ip_mchField = value;
                this.RaisePropertyChanged("ip_mch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string ip_lbl {
            get {
                return this.ip_lblField;
            }
            set {
                this.ip_lblField = value;
                this.RaisePropertyChanged("ip_lbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> ip_qty {
            get {
                return this.ip_qtyField;
            }
            set {
                this.ip_qtyField = value;
                this.RaisePropertyChanged("ip_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string ip_rsn {
            get {
                return this.ip_rsnField;
            }
            set {
                this.ip_rsnField = value;
                this.RaisePropertyChanged("ip_rsn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:MES2QAD_AS", ConfigurationName="QADServices.MES2QAD_ASObj")]
    public interface MES2QAD_ASObj {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MES2QAD_AS:MES2QAD_AS) of message xxm2q01Request does not match the default value (urn:MES2QAD_AS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Linxens.Core.QADServices.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Linxens.Core.QADServices.xxm2q01Response xxm2q01(Linxens.Core.QADServices.xxm2q01Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MES2QAD_AS:MES2QAD_AS) of message xxf2q01Request does not match the default value (urn:MES2QAD_AS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Linxens.Core.QADServices.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Linxens.Core.QADServices.xxf2q01Response xxf2q01(Linxens.Core.QADServices.xxf2q01Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="xxm2q01", WrapperNamespace="urn:MES2QAD_AS:MES2QAD_AS", IsWrapped=true)]
    public partial class xxm2q01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip_AuthKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip_User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip_domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tt_golf_dataRow", IsNullable=false)]
        public Linxens.Core.QADServices.xxm2q01_tt_golf_dataRow[] tt_golf_data;
        
        public xxm2q01Request() {
        }
        
        public xxm2q01Request(string ip_AuthKey, string ip_User, string ip_domain, Linxens.Core.QADServices.xxm2q01_tt_golf_dataRow[] tt_golf_data) {
            this.ip_AuthKey = ip_AuthKey;
            this.ip_User = ip_User;
            this.ip_domain = ip_domain;
            this.tt_golf_data = tt_golf_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="xxm2q01Response", WrapperNamespace="urn:MES2QAD_AS:MES2QAD_AS", IsWrapped=true)]
    public partial class xxm2q01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string op_ReturnStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tt_Error_WarningRow", IsNullable=false)]
        public Linxens.Core.QADServices.xxm2q01_tt_Error_WarningRow[] tt_Error_Warning;
        
        public xxm2q01Response() {
        }
        
        public xxm2q01Response(string result, string op_ReturnStatus, Linxens.Core.QADServices.xxm2q01_tt_Error_WarningRow[] tt_Error_Warning) {
            this.result = result;
            this.op_ReturnStatus = op_ReturnStatus;
            this.tt_Error_Warning = tt_Error_Warning;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS")]
    public partial class xxf2q01_tt_golf_dataRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> ip_srnoField;
        
        private string ip_empField;
        
        private string ip_tr_typeField;
        
        private string ip_lineField;
        
        private string ip_partField;
        
        private System.Nullable<int> ip_opField;
        
        private string ip_wcField;
        
        private string ip_mchField;
        
        private string ip_lblField;
        
        private string ip_t_lblField;
        
        private System.Nullable<decimal> ip_qtyField;
        
        private string ip_rsnField;
        
        private System.Nullable<int> ip_defectsField;
        
        private System.Nullable<int> ip_splicesField;
        
        private string ip_p_dateField;
        
        private string ip_printerField;
        
        private string ip_shiptoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> ip_srno {
            get {
                return this.ip_srnoField;
            }
            set {
                this.ip_srnoField = value;
                this.RaisePropertyChanged("ip_srno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ip_emp {
            get {
                return this.ip_empField;
            }
            set {
                this.ip_empField = value;
                this.RaisePropertyChanged("ip_emp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ip_tr_type {
            get {
                return this.ip_tr_typeField;
            }
            set {
                this.ip_tr_typeField = value;
                this.RaisePropertyChanged("ip_tr_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ip_line {
            get {
                return this.ip_lineField;
            }
            set {
                this.ip_lineField = value;
                this.RaisePropertyChanged("ip_line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ip_part {
            get {
                return this.ip_partField;
            }
            set {
                this.ip_partField = value;
                this.RaisePropertyChanged("ip_part");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> ip_op {
            get {
                return this.ip_opField;
            }
            set {
                this.ip_opField = value;
                this.RaisePropertyChanged("ip_op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ip_wc {
            get {
                return this.ip_wcField;
            }
            set {
                this.ip_wcField = value;
                this.RaisePropertyChanged("ip_wc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ip_mch {
            get {
                return this.ip_mchField;
            }
            set {
                this.ip_mchField = value;
                this.RaisePropertyChanged("ip_mch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string ip_lbl {
            get {
                return this.ip_lblField;
            }
            set {
                this.ip_lblField = value;
                this.RaisePropertyChanged("ip_lbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ip_t_lbl {
            get {
                return this.ip_t_lblField;
            }
            set {
                this.ip_t_lblField = value;
                this.RaisePropertyChanged("ip_t_lbl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> ip_qty {
            get {
                return this.ip_qtyField;
            }
            set {
                this.ip_qtyField = value;
                this.RaisePropertyChanged("ip_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string ip_rsn {
            get {
                return this.ip_rsnField;
            }
            set {
                this.ip_rsnField = value;
                this.RaisePropertyChanged("ip_rsn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> ip_defects {
            get {
                return this.ip_defectsField;
            }
            set {
                this.ip_defectsField = value;
                this.RaisePropertyChanged("ip_defects");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> ip_splices {
            get {
                return this.ip_splicesField;
            }
            set {
                this.ip_splicesField = value;
                this.RaisePropertyChanged("ip_splices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string ip_p_date {
            get {
                return this.ip_p_dateField;
            }
            set {
                this.ip_p_dateField = value;
                this.RaisePropertyChanged("ip_p_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string ip_printer {
            get {
                return this.ip_printerField;
            }
            set {
                this.ip_printerField = value;
                this.RaisePropertyChanged("ip_printer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string ip_shipto {
            get {
                return this.ip_shiptoField;
            }
            set {
                this.ip_shiptoField = value;
                this.RaisePropertyChanged("ip_shipto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS")]
    public partial class xxf2q01_tt_Error_WarningRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tterr_typeField;
        
        private System.Nullable<int> tterr_srnoField;
        
        private string tterr_codeField;
        
        private string tterr_descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string tterr_type {
            get {
                return this.tterr_typeField;
            }
            set {
                this.tterr_typeField = value;
                this.RaisePropertyChanged("tterr_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> tterr_srno {
            get {
                return this.tterr_srnoField;
            }
            set {
                this.tterr_srnoField = value;
                this.RaisePropertyChanged("tterr_srno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string tterr_code {
            get {
                return this.tterr_codeField;
            }
            set {
                this.tterr_codeField = value;
                this.RaisePropertyChanged("tterr_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string tterr_desc {
            get {
                return this.tterr_descField;
            }
            set {
                this.tterr_descField = value;
                this.RaisePropertyChanged("tterr_desc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="xxf2q01", WrapperNamespace="urn:MES2QAD_AS:MES2QAD_AS", IsWrapped=true)]
    public partial class xxf2q01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip_AuthKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip_User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip_domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tt_golf_dataRow", IsNullable=false)]
        public Linxens.Core.QADServices.xxf2q01_tt_golf_dataRow[] tt_golf_data;
        
        public xxf2q01Request() {
        }
        
        public xxf2q01Request(string ip_AuthKey, string ip_User, string ip_domain, Linxens.Core.QADServices.xxf2q01_tt_golf_dataRow[] tt_golf_data) {
            this.ip_AuthKey = ip_AuthKey;
            this.ip_User = ip_User;
            this.ip_domain = ip_domain;
            this.tt_golf_data = tt_golf_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="xxf2q01Response", WrapperNamespace="urn:MES2QAD_AS:MES2QAD_AS", IsWrapped=true)]
    public partial class xxf2q01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string op_ReturnStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:MES2QAD_AS:MES2QAD_AS", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tt_Error_WarningRow", IsNullable=false)]
        public Linxens.Core.QADServices.xxf2q01_tt_Error_WarningRow[] tt_Error_Warning;
        
        public xxf2q01Response() {
        }
        
        public xxf2q01Response(string result, string op_ReturnStatus, Linxens.Core.QADServices.xxf2q01_tt_Error_WarningRow[] tt_Error_Warning) {
            this.result = result;
            this.op_ReturnStatus = op_ReturnStatus;
            this.tt_Error_Warning = tt_Error_Warning;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MES2QAD_ASObjChannel : Linxens.Core.QADServices.MES2QAD_ASObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MES2QAD_ASObjClient : System.ServiceModel.ClientBase<Linxens.Core.QADServices.MES2QAD_ASObj>, Linxens.Core.QADServices.MES2QAD_ASObj {
        
        public MES2QAD_ASObjClient() {
        }
        
        public MES2QAD_ASObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MES2QAD_ASObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MES2QAD_ASObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MES2QAD_ASObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Linxens.Core.QADServices.xxm2q01Response Linxens.Core.QADServices.MES2QAD_ASObj.xxm2q01(Linxens.Core.QADServices.xxm2q01Request request) {
            return base.Channel.xxm2q01(request);
        }
        
        public string xxm2q01(string ip_AuthKey, string ip_User, string ip_domain, Linxens.Core.QADServices.xxm2q01_tt_golf_dataRow[] tt_golf_data, out string op_ReturnStatus, out Linxens.Core.QADServices.xxm2q01_tt_Error_WarningRow[] tt_Error_Warning) {
            Linxens.Core.QADServices.xxm2q01Request inValue = new Linxens.Core.QADServices.xxm2q01Request();
            inValue.ip_AuthKey = ip_AuthKey;
            inValue.ip_User = ip_User;
            inValue.ip_domain = ip_domain;
            inValue.tt_golf_data = tt_golf_data;
            Linxens.Core.QADServices.xxm2q01Response retVal = ((Linxens.Core.QADServices.MES2QAD_ASObj)(this)).xxm2q01(inValue);
            op_ReturnStatus = retVal.op_ReturnStatus;
            tt_Error_Warning = retVal.tt_Error_Warning;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Linxens.Core.QADServices.xxf2q01Response Linxens.Core.QADServices.MES2QAD_ASObj.xxf2q01(Linxens.Core.QADServices.xxf2q01Request request) {
            return base.Channel.xxf2q01(request);
        }
        
        public string xxf2q01(string ip_AuthKey, string ip_User, string ip_domain, Linxens.Core.QADServices.xxf2q01_tt_golf_dataRow[] tt_golf_data, out string op_ReturnStatus, out Linxens.Core.QADServices.xxf2q01_tt_Error_WarningRow[] tt_Error_Warning) {
            Linxens.Core.QADServices.xxf2q01Request inValue = new Linxens.Core.QADServices.xxf2q01Request();
            inValue.ip_AuthKey = ip_AuthKey;
            inValue.ip_User = ip_User;
            inValue.ip_domain = ip_domain;
            inValue.tt_golf_data = tt_golf_data;
            Linxens.Core.QADServices.xxf2q01Response retVal = ((Linxens.Core.QADServices.MES2QAD_ASObj)(this)).xxf2q01(inValue);
            op_ReturnStatus = retVal.op_ReturnStatus;
            tt_Error_Warning = retVal.tt_Error_Warning;
            return retVal.result;
        }
    }
}
